services:
  - type: web
    name: watermelon-dating
    env: node
    plan: free
    autoDeploy: true
    region: oregon
    buildCommand: |
      corepack enable
      pnpm install --frozen-lockfile
      pnpm build
    startCommand: pnpm start -- -p $PORT
    envVars:
      - key: NODE_ENV
        value: production
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        sync: false

